import strawberry from "../../../art/source/crops/spring/strawberry-growth-sheet.png?url";
import peas from "../../../art/source/crops/spring/peas-growth-sheet.png?url";
import radish from "../../../art/source/crops/spring/radish-growth-sheet.png?url";
import tulip from "../../../art/source/crops/spring/tulip-growth-sheet.png?url";
import chicken from "../../../art/source/animals/spring/chicken-pose-sheet.png?url";
import rabbit from "../../../art/source/animals/spring/rabbit-pose-sheet.png?url";
import summerRoster from "../../../art/source/seasons/summer/roster-sheet.png?url";
import rainyRoster from "../../../art/source/seasons/rainy/roster-sheet.png?url";
import autumnRoster from "../../../art/source/seasons/autumn/roster-sheet.png?url";
import winterRoster from "../../../art/source/seasons/winter/roster-sheet.png?url";
export const CROP_SHEETS = { strawberry, peas, radish, tulip };
export const ANIMAL_SHEETS = { chicken, rabbit };
export const ROSTERS = { summer: summerRoster, rainy: rainyRoster, autumn: autumnRoster, winter: winterRoster };
